---
title: "Final Project Part 1"
author: "Jaival Desai, Rui Liang, Jiayu Lin, Zenan Ye"
date: "4/15/2020"
output: html_document
---
```{r, warning=FALSE, message=FALSE}
library(quantmod)
library(lattice)
library(timeSeries)
library(rugarch)
library(clordr)
```

```{r,warning=FALSE,message=FALSE}
#Obtain the NASDAQ returns and remove the NA values
getSymbols("^TNX", from="1990-01-01")
TNX <- na.omit(TNX)
returns  <- diff(log(Cl(TNX)))
returns [as.character(head(index(Cl(TNX)),1))] = 0


#Make a forecast vector to store the predictions

windowlength  <- 500
forecastlength <- length(returns) - windowlength
forecastvector <- vector(mode = "character", length = forecastlength)
```

```{r}
for (i in 0:forecastlength){
  #Find the sliding window for each day
  returnsoffset <- returns[(1+i):(windowlength+i)]
  
  #Fit the optimal ARIMA model
  final.aic <- Inf
  final.order <- c(0,0,0)
  for (p in 0:5) for (q in 0:5) {
      if ( p == 0 && q == 0) {
          next
      }
      arimaFit <- tryCatch(arima(returnsoffset, order = c(p,0,q)),
                           error = function(err) FALSE, warning = function(err) FALSE)
      if(! is.logical(arimaFit)){
        current.aic <- AIC(arimaFit)
        if (current.aic < final.aic){
          final.aic <- current.aic
          final.order <- c(p,0,q)
          final.arima <- arima(returnsoffset,order = final.order)
        }
      }else{
        next
      }
  }
  #FIT the GARCH model 
  specify <- ugarchspec(variance.model = list(garchOrder =c(1,1)),
                        mean.model = list(armaOrder = c(final.order[1],final.order[3]),include.mean = TRUE)
                        ,distribution.model = "sged")
  fit <- tryCatch(ugarchfit(specify,returnsoffset,solver = "hybrid"),
                  error = function(e) e,
                  warning = function(w) w)
  if(is(fit,"warning")){
    forecastvector[i+1] <-paste(index(returnsoffset[windowlength]),1,sep = ",")
  }else{
    fore <- ugarchforecast(fit,n.ahead = 1)
    ind <- fore@forecast$seriesFor
    forecastvector[i+1] <- paste(colnames(ind),
                            ifelse(ind[1]<0,1,-1),sep = ",")
  }
}
```

```{r}
write.csv(forecastvector, file="forecasts.csv", row.names=FALSE)
data <- read.csv("forecasts_new.csv")
ArimaGarch <- as.xts( 
  read.zoo(
    file="forecasts_new.csv", format="%Y-%m-%d", header=F, sep=","
  )
)
```

```{r}
Intersect <- merge( ArimaGarch[,1], returns, all=F )
ArimaGarchReturns <- Intersect[,1] * Intersect[,2]

ArimaGarchCurve <- log( cumprod( 1 + ArimaGarchReturns ) )
BuyHoldCurve <- log( cumprod( 1 + Intersect[,2] ) )
CombinedCurve <- merge(ArimaGarchCurve, BuyHoldCurve, all=F )

xyplot( 
  CombinedCurve,
  superpose=T,
  col=c("darkred", "darkblue"),
  lwd=2,
  key=list( 
    text=list(
      c("ARIMA+GARCH", "Buy & Hold")
    ),
    lines=list(
      lwd=2, col=c("darkred", "darkblue")
    )
  )
)
nrow(data[data$Value == -1,])
```

